### PR TITLE
sửa wishlist sang ajax

### PR DESCRIPTION
**Pull request by hoangnh1211**
## Related Tickets
- https://edu-redmine.sun-asterisk.vn/issues/41663

## WHAT
- sửa wishlist sang ajax

## HOW
- N/A

## WHY
- N/A

### CODE REVIEW

**Comment by hoangnh1211** [comment]
ready

**Review by huongnt-2545 — COMMENTED** [review]
pull có 2 commit nha

**Comment by hoangnh1211** [comment]
ready

**Review by huongnt-2545 — APPROVED** [review]
merged

**Pull request merged**
